name: Merge SuiteSpot into Template
on: { workflow_dispatch: {} }
permissions: { contents: write }
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: sudo apt-get update -y && sudo apt-get install -y unzip git
      - run: bash tools/merge_suitespot.sh
      - env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat: merged SuiteSpot into template; patched Program Files default; stripped comments; regenerated project files"
            git push origin HEAD:main
          fi
